## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Heimdall"
copyright = "{year}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "term"]
# googleAnalytics = "G-XXXXXXXXXX"

[markup]
[markup.highlight]
  style = 'github-dark'
  tabWidth = 4
[markup.tableOfContents]
  endLevel = 2
  ordered = false

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]

[Params.social]

[Params.asset]
