## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

theme = "hugo-story"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "term"]
# googleAnalytics = "your-google-analytics-id"

[markup]
  [markup.tableOfContents]
    endLevel = 2
    ordered = false

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]

[Params.social]
